[pytest]
pythonpath = .
#norecursedirs = docs *.egg-info .git .idea alembic alembic_sqlite db routes auth  storage .tox __pycache__
addopts = -v --cov=meshwork --cov-report=term-missing --strict-markers -m "not integration" tests/
python_files = test_*
markers =
    integration: tests that require external services such as Docker containers
